import 'reflect-metadata';
import { AppModule } from '../app.module';
import { CurrentSession } from '../common/decorators/current-session.decorator';
import { PaginationQueryDto } from '../common/dto/pagination-query.dto';
import { PaginationMetaDto } from '../common/dto/pagination-response.dto';
import { ApiException } from '../common/exceptions/api.exception';
import { AccessTokenGuard } from '../common/guards/access-token.guard';
import configuration from '../configs/configuration';
import datasource from '../database/datasource';
import seedDatasource from '../database/seed';
import { CreateUniqueSeedsTable1732310000000 } from '../database/migrations/1702310000000-CreateUniqueSeedsTable';
import { CreateAtrioSchema1718300000000 } from '../database/migrations/1718300000000-CreateAtrioSchema';
import { CreateHotelsTable1718300000001 } from '../database/migrations/1718300000001-CreateHotelsTable';
import { CreateGuestsTable1718300000002 } from '../database/migrations/1718300000002-CreateGuestsTable';
import { CreateStaysTable1718300000003 } from '../database/migrations/1718300000003-CreateStaysTable';
import { CreateStayUsefulInfoTable1718300000004 } from '../database/migrations/1718300000004-CreateStayUsefulInfoTable';
import { CreateConsumptionItemsTable1718300000005 } from '../database/migrations/1718300000005-CreateConsumptionItemsTable';
import { CreateGuestSessionsTable1718300000006 } from '../database/migrations/1718300000006-CreateGuestSessionsTable';
import { CreateServiceDefinitionsTable1718300000007 } from '../database/migrations/1718300000007-CreateServiceDefinitionsTable';
import { CreateExperienceCollectionsTable1718300000008 } from '../database/migrations/1718300000008-CreateExperienceCollectionsTable';
import { CreateExperiencesTable1718300000009 } from '../database/migrations/1718300000009-CreateExperiencesTable';
import { CreateExperienceCollectionItemsTable1718300000010 } from '../database/migrations/1718300000010-CreateExperienceCollectionItemsTable';
import { CreateExperienceAvailabilitySlotsTable1718300000011 } from '../database/migrations/1718300000011-CreateExperienceAvailabilitySlotsTable';
import { CreateStayRequestsTable1718300000012 } from '../database/migrations/1718300000012-CreateStayRequestsTable';
import { CreateReservationsTable1718300000013 } from '../database/migrations/1718300000013-CreateReservationsTable';
import { CreateConciergeMessagesTable1718300000014 } from '../database/migrations/1718300000014-CreateConciergeMessagesTable';
import { seedAvailabilitySlots, seedCollections, seedCollectionItems, seedConciergeMessages, seedConsumptionItems, seedExperiences, seedGuest, seedHotel, seedRequests, seedReservations, seedServices, seedStay, seedStayUsefulInfo } from '../database/seeds/data/ui-mock-seed.data';
import InitialSeeder from '../database/seeds/initial.seeder';
import UniqueSeeder from '../database/seeds/unique.seeder';
import { AuthModule } from '../modules/auth/auth.module';
import { SessionController } from '../modules/auth/controllers/session.controller';
import { StayAccessController } from '../modules/auth/controllers/stay-access.controller';
import { IdentifyStayAccessDto, ResendStayAccessCodeDto, SessionResponseDto, StayAccessChallengeResponseDto, VerifyStayAccessDto, VerifyStayAccessResponseDto } from '../modules/auth/dto/stay-access.dto';
import { GuestSession } from '../modules/auth/entities/guest-session.entity';
import { GuestSessionRepository } from '../modules/auth/repositories/guest-session.repository';
import { ConciergeModule } from '../modules/concierge/concierge.module';
import { ConciergeController } from '../modules/concierge/controllers/concierge.controller';
import { ConciergeListQueryDto, ConciergeMessageDto, ConciergeMessagesResponseDto, CreateConciergeMessageDto, CreateConciergeMessageResponseDto } from '../modules/concierge/dto/concierge.dto';
import { ConciergeMessage } from '../modules/concierge/entities/concierge-message.entity';
import { ConciergeMessageRepository } from '../modules/concierge/repositories/concierge-message.repository';
import { ExperiencesController } from '../modules/experiences/controllers/experiences.controller';
import { ExperienceAvailabilityResponseDto, ExperienceCollectionDetailResponseDto, ExperienceCollectionsResponseDto, ExperienceDetailResponseDto, ExperiencesQueryDto } from '../modules/experiences/dto/experiences.dto';
import { ExperienceAvailabilitySlot } from '../modules/experiences/entities/experience-availability-slot.entity';
import { ExperienceCollectionItem } from '../modules/experiences/entities/experience-collection-item.entity';
import { ExperienceCollection } from '../modules/experiences/entities/experience-collection.entity';
import { Experience } from '../modules/experiences/entities/experience.entity';
import { ExperiencesModule } from '../modules/experiences/experiences.module';
import { ExperienceRepository } from '../modules/experiences/repositories/experience.repository';
import { LoggerModule } from '../modules/logger/logger.module';
import { LogstashLogger } from '../modules/logger/logstash.logger';
import { QUEUE_SERVICE } from '../modules/queues/constants/queue.constants';
import { QueuesModule } from '../modules/queues/queues.module';
import { QueueService } from '../modules/queues/services/queue.service';
import { RedisFifoQueueService } from '../modules/queues/services/redis-fifo-queue.service';
import { SqsQueueService } from '../modules/queues/services/sqs-queue.service';
import { RedisModule } from '../modules/redis/redis.module';
import RedisService from '../modules/redis/services/redis.service';
import { RequestsController } from '../modules/requests/controllers/requests.controller';
import { CreateStayRequestDto, StayRequestItemDto, StayRequestListQueryDto, StayRequestListResponseDto } from '../modules/requests/dto/requests.dto';
import { StayRequest } from '../modules/requests/entities/stay-request.entity';
import { StayRequestRepository } from '../modules/requests/repositories/stay-request.repository';
import { RequestsModule } from '../modules/requests/requests.module';
import { ReservationsController } from '../modules/reservations/controllers/reservations.controller';
import { CreateReservationDto, ReservationItemDto, ReservationListQueryDto, ReservationListResponseDto } from '../modules/reservations/dto/reservations.dto';
import { Reservation } from '../modules/reservations/entities/reservation.entity';
import { ReservationRepository } from '../modules/reservations/repositories/reservation.repository';
import { ReservationsModule } from '../modules/reservations/reservations.module';
import { S3Module } from '../modules/s3/s3.module';
import { S3Service } from '../modules/s3/services/s3.service';
import { ServicesController } from '../modules/services/controllers/services.controller';
import { ServiceDetailResponseDto, ServiceListResponseDto, ServicesQueryDto } from '../modules/services/dto/services.dto';
import { ServiceDefinition } from '../modules/services/entities/service-definition.entity';
import { ServiceCatalogRepository } from '../modules/services/repositories/service-catalog.repository';
import { ServicesModule } from '../modules/services/services.module';
import { ServiceCatalogService } from '../modules/services/services/service-catalog.service';
import { SqsService } from '../modules/sqs/services/sqs.service';
import { SqsModule } from '../modules/sqs/sqs.module';
import { StaysController } from '../modules/stays/controllers/stays.controller';
import { ConsumptionResponseDto } from '../modules/stays/dto/consumption-response.dto';
import { DashboardResponseDto } from '../modules/stays/dto/dashboard-response.dto';
import { StayResponseDto, WifiResponseDto } from '../modules/stays/dto/stay-response.dto';
import { ConsumptionItem } from '../modules/stays/entities/consumption-item.entity';
import { Guest } from '../modules/stays/entities/guest.entity';
import { Hotel } from '../modules/stays/entities/hotel.entity';
import { StayUsefulInfo } from '../modules/stays/entities/stay-useful-info.entity';
import { Stay } from '../modules/stays/entities/stay.entity';
import { StayRepository } from '../modules/stays/repositories/stay.repository';
import { StaysModule } from '../modules/stays/stays.module';
import { STORAGE_SERVICE } from '../modules/storage/constants/storage.constants';
import { LocalStorageService } from '../modules/storage/services/local-storage.service';
import { S3StorageService } from '../modules/storage/services/s3-storage.service';
import { StorageService } from '../modules/storage/services/storage.service';
import { StorageModule } from '../modules/storage/storage.module';
import { HttpExceptionFilter } from '../modules/utils/exceptions/http.exception.filter';
import { NewrelicInterceptor } from '../modules/utils/interceptors/newrelic.interceptor';
import { SuccessLoggingInterceptor } from '../modules/utils/interceptors/success.logging.interceptor';

describe('smoke imports', () => {
  it('loads exported classes and constants', () => {
    expect(AppModule).toBeDefined();
    expect(CurrentSession).toBeDefined();
    expect(PaginationQueryDto).toBeDefined();
    expect(PaginationMetaDto).toBeDefined();
    expect(ApiException).toBeDefined();
    expect(AccessTokenGuard).toBeDefined();
    expect(configuration).toBeDefined();
    expect(datasource).toBeDefined();
    expect(seedDatasource).toBe(datasource);
    expect(CreateUniqueSeedsTable1732310000000).toBeDefined();
    expect(CreateAtrioSchema1718300000000).toBeDefined();
    expect(CreateHotelsTable1718300000001).toBeDefined();
    expect(CreateGuestsTable1718300000002).toBeDefined();
    expect(CreateStaysTable1718300000003).toBeDefined();
    expect(CreateStayUsefulInfoTable1718300000004).toBeDefined();
    expect(CreateConsumptionItemsTable1718300000005).toBeDefined();
    expect(CreateGuestSessionsTable1718300000006).toBeDefined();
    expect(CreateServiceDefinitionsTable1718300000007).toBeDefined();
    expect(CreateExperienceCollectionsTable1718300000008).toBeDefined();
    expect(CreateExperiencesTable1718300000009).toBeDefined();
    expect(CreateExperienceCollectionItemsTable1718300000010).toBeDefined();
    expect(CreateExperienceAvailabilitySlotsTable1718300000011).toBeDefined();
    expect(CreateStayRequestsTable1718300000012).toBeDefined();
    expect(CreateReservationsTable1718300000013).toBeDefined();
    expect(CreateConciergeMessagesTable1718300000014).toBeDefined();
    expect(seedHotel.id).toBe('copacabana-palace');
    expect(seedGuest.id).toBe('guest_001');
    expect(seedStay.id).toBe('stay_001');
    expect(seedStayUsefulInfo).toHaveLength(9);
    expect(seedServices.length).toBeGreaterThan(1);
    expect(seedCollections.length).toBeGreaterThan(1);
    expect(seedExperiences.length).toBeGreaterThan(1);
    expect(seedCollectionItems.length).toBeGreaterThan(1);
    expect(seedAvailabilitySlots.length).toBeGreaterThan(1);
    expect(seedRequests).toHaveLength(1);
    expect(seedReservations).toHaveLength(1);
    expect(seedConciergeMessages).toHaveLength(1);
    expect(seedConsumptionItems.length).toBeGreaterThan(1);
    expect(InitialSeeder).toBeDefined();
    expect(UniqueSeeder).toBeDefined();
    expect(AuthModule).toBeDefined();
    expect(SessionController).toBeDefined();
    expect(StayAccessController).toBeDefined();
    expect(IdentifyStayAccessDto).toBeDefined();
    expect(ResendStayAccessCodeDto).toBeDefined();
    expect(SessionResponseDto).toBeDefined();
    expect(StayAccessChallengeResponseDto).toBeDefined();
    expect(VerifyStayAccessDto).toBeDefined();
    expect(VerifyStayAccessResponseDto).toBeDefined();
    expect(GuestSession).toBeDefined();
    expect(GuestSessionRepository).toBeDefined();
    expect(ConciergeModule).toBeDefined();
    expect(ConciergeController).toBeDefined();
    expect(ConciergeListQueryDto).toBeDefined();
    expect(ConciergeMessageDto).toBeDefined();
    expect(ConciergeMessagesResponseDto).toBeDefined();
    expect(CreateConciergeMessageDto).toBeDefined();
    expect(CreateConciergeMessageResponseDto).toBeDefined();
    expect(ConciergeMessage).toBeDefined();
    expect(ConciergeMessageRepository).toBeDefined();
    expect(ExperiencesController).toBeDefined();
    expect(ExperienceAvailabilityResponseDto).toBeDefined();
    expect(ExperienceCollectionDetailResponseDto).toBeDefined();
    expect(ExperienceCollectionsResponseDto).toBeDefined();
    expect(ExperienceDetailResponseDto).toBeDefined();
    expect(ExperiencesQueryDto).toBeDefined();
    expect(ExperienceAvailabilitySlot).toBeDefined();
    expect(ExperienceCollectionItem).toBeDefined();
    expect(ExperienceCollection).toBeDefined();
    expect(Experience).toBeDefined();
    expect(ExperiencesModule).toBeDefined();
    expect(ExperienceRepository).toBeDefined();
    expect(LoggerModule).toBeDefined();
    expect(LogstashLogger).toBeDefined();
    expect(QUEUE_SERVICE).toBeDefined();
    expect(QueuesModule).toBeDefined();
    expect(QueueService).toBeDefined();
    expect(RedisFifoQueueService).toBeDefined();
    expect(SqsQueueService).toBeDefined();
    expect(RedisModule).toBeDefined();
    expect(RedisService).toBeDefined();
    expect(RequestsController).toBeDefined();
    expect(CreateStayRequestDto).toBeDefined();
    expect(StayRequestItemDto).toBeDefined();
    expect(StayRequestListQueryDto).toBeDefined();
    expect(StayRequestListResponseDto).toBeDefined();
    expect(StayRequest).toBeDefined();
    expect(StayRequestRepository).toBeDefined();
    expect(RequestsModule).toBeDefined();
    expect(ReservationsController).toBeDefined();
    expect(CreateReservationDto).toBeDefined();
    expect(ReservationItemDto).toBeDefined();
    expect(ReservationListQueryDto).toBeDefined();
    expect(ReservationListResponseDto).toBeDefined();
    expect(Reservation).toBeDefined();
    expect(ReservationRepository).toBeDefined();
    expect(ReservationsModule).toBeDefined();
    expect(S3Module).toBeDefined();
    expect(S3Service).toBeDefined();
    expect(ServicesController).toBeDefined();
    expect(ServiceDetailResponseDto).toBeDefined();
    expect(ServiceListResponseDto).toBeDefined();
    expect(ServicesQueryDto).toBeDefined();
    expect(ServiceDefinition).toBeDefined();
    expect(ServiceCatalogRepository).toBeDefined();
    expect(ServicesModule).toBeDefined();
    expect(ServiceCatalogService).toBeDefined();
    expect(SqsService).toBeDefined();
    expect(SqsModule).toBeDefined();
    expect(StaysController).toBeDefined();
    expect(ConsumptionResponseDto).toBeDefined();
    expect(DashboardResponseDto).toBeDefined();
    expect(StayResponseDto).toBeDefined();
    expect(WifiResponseDto).toBeDefined();
    expect(ConsumptionItem).toBeDefined();
    expect(Guest).toBeDefined();
    expect(Hotel).toBeDefined();
    expect(StayUsefulInfo).toBeDefined();
    expect(Stay).toBeDefined();
    expect(StayRepository).toBeDefined();
    expect(StaysModule).toBeDefined();
    expect(STORAGE_SERVICE).toBeDefined();
    expect(LocalStorageService).toBeDefined();
    expect(S3StorageService).toBeDefined();
    expect(StorageService).toBeDefined();
    expect(StorageModule).toBeDefined();
    expect(HttpExceptionFilter).toBeDefined();
    expect(NewrelicInterceptor).toBeDefined();
    expect(SuccessLoggingInterceptor).toBeDefined();
  });
});
